### ISSUE TITLE
Communication issue

### ISSUE THREAD

**Issue by 4l3x777** [eversinc33/Banshee#2]
Hello mate! Nice job! 
I tested your project and found some troubles with communication. 
Driver create objects:

```C++
BeCreateNamedEvent(&commandEvent, &commandEventName, FALSE);
BeCreateNamedEvent(&answerEvent, &answerEventName, FALSE);
BeCreateSharedMemory(&hSharedMemory, &pSharedMemory);
```
with SYSTEM token integrity.
So Client need to have SYSTEM token for communicate with driver.
Why I can't to use local administrator token for communication? 
I think that is possible to make low integrity HANDLEs in Driver. 
In user-space if Driver is load, you can open Driver's HANDLE with low integrity token.

**Comment by eversinc33** [comment]
Hey, thx. I dont know what you mean with needing system token, administrator privileges are enough to run the client and connect. You are talking about the shared memory handle I believe? I will have to look into the ACL code, this was planned to adjust so that a low priv user can write commands as well. Thanks for reminding me,  I was too lazy til now but I will get this fixed asap.

**Comment by eversinc33** [comment]
Fixed. Now accessible from any authenticated user. Thank you!
